=== bernal199/40270/xml/musica.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT biblioteca (canciones)>
<!ELEMENT canciones (cancion+)>
<!ELEMENT cancion (titulo, artista, genero)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT artista (#PCDATA)>
<!ELEMENT genero (#PCDATA)>

=== bernal199/40270/xml/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "musica.dtd">
<biblioteca>
    <canciones>
        <cancion>
            <titulo>kool aid</titulo>
            <artista>Bring me the horizon</artista>
            <genero>metal</genero>
        </cancion>
        <cancion>
            <titulo>Eyes without a face</titulo>
            <artista>Billy idol</artista>
            <genero>pop</genero>
        </cancion>
    </canciones>
</biblioteca>
